name: unleash_proxy
description: Unleash Flutter Proxy SDK. Unleash is an open-source feature flag service.
homepage: https://github.com/rizentium/unleash-flutter-proxy-sdk
repository: https://github.com/rizentium/unleash-flutter-proxy-sdk
issue_tracker: https://github.com/rizentium/unleash-flutter-proxy-sdk/issues
version: 0.2.2

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
